language: node_js
node_js:
- '0.10'
branches:
  only:
  - master
env:
  global:
  - GIT_COMMITTER_NAME=kimjmin
  - GIT_AUTHOR_NAME=Jongmin Kim
  - secure: Wy3ZemZzVEtiARjgLboW9yNcZT42fSCzG4KsJ9cXy4ZLcgeh81GFfWwVjl1HqW/p41tTMPs/wyEyn04VQaDsmyvOGuDsfyD2chyzSyr8gheEKEHDNur6YPQNosTTY2D7xOu8VQhZoGOFvfq6PII9ty5PPvPy/Ug+70mMZiSyhVk=
before_script:
- npm install -g bower
- npm install -g docpad
- npm install
- bower install
- git remote add target https://$GH_TOKEN@github.com/kimjmin/kimjmin.github.io.git
script: docpad deploy-ghpages --env static
